Repository zetkin/www.zetk.in, pull requests merged in 2018-05, with the labels that each got.

#183 Enhancement/my pages redesign
  locale/dashboard/da.yaml
  locale/dashboard/en.yaml
  locale/dashboard/sv.yaml
  locale/pages/dashboardPage/en.yaml
  locale/pages/dashboardPage/sv.yaml
  src/components/dashboard/ActionList.scss
  src/components/dashboard/Dashboard.jsx
  src/components/dashboard/Dashboard.scss
  src/components/misc/ConnectionList.jsx
  src/components/misc/ConnectionList.scss
  src/components/pages/DashboardPage.jsx
  src/components/pages/dashboard/DashboardHero.jsx
  src/components/pages/dashboard/DashboardHero.scss
  src/components/pages/dashboard/DashboardMenu.jsx
  src/components/pages/dashboard/DashboardMenu.scss
  src/components/pages/dashboard/DashboardMenuItem.jsx
  src/components/pages/dashboard/DashboardMenuItem.scss
  src/components/pages/dashboard/DashboardPage.jsx
  src/components/pages/dashboard/sections/ActionList.jsx
  src/components/pages/dashboard/sections/ActionList.scss
  src/components/pages/dashboard/sections/AssignmentList.jsx
  src/components/pages/dashboard/sections/AssignmentList.scss
  src/components/pages/dashboard/sections/CallSectionPage.jsx
  src/components/pages/dashboard/sections/CallSectionPage.scss
  src/components/pages/dashboard/sections/CampaignList.jsx
  src/components/pages/dashboard/sections/CampaignList.scss
  src/components/pages/dashboard/sections/CampaignSectionPage.jsx
  src/components/pages/dashboard/sections/CampaignSectionPage.scss
  src/components/pages/dashboard/sections/OrgSectionPage.jsx
  src/components/pages/dashboard/sections/OrgSectionPage.scss
  src/components/pages/dashboard/sections/SectionPage.jsx
  src/components/pages/dashboard/sections/SectionPage.scss
  src/components/pages/index.js
  src/components/routes.jsx
  src/scss/_global.scss
  src/scss/_mixins.scss
  src/scss/_variables.scss
  src/server/app.js
  src/server/preloader.js
Labels: enhancement

#185 Recommended organizations
  locale/misc/en.yaml
  locale/misc/sv.yaml
  locale/misc/welcome/en.yaml
  locale/misc/welcome/sv.yaml
  locale/pages/dashboardPage/en.yaml
  src/actions/index.js
  src/actions/org.js
  src/components/misc/Welcome.jsx
  src/components/misc/Welcome.scss
  src/components/pages/dashboard/sections/ActionList.jsx
  src/components/pages/dashboard/sections/AssignmentList.jsx
  src/components/pages/dashboard/sections/CampaignList.jsx
  src/components/pages/org/OrgPage.jsx
  src/store/orgs.js
Labels: feature

#190 Retrieve call assignments on dashboard mount
  src/components/pages/dashboard/DashboardPage.jsx
Labels: bug
