Repository zetkin/www.zetk.in, pull requests merged in 2018-07, with the labels that each got.

#223 Open campaigns
  locale/pages/campaign/en.yaml
  locale/pages/campaign/sv.yaml
  src/components/misc/GoogleAnalytics.jsx
  src/components/pages/CampaignPage.jsx
  src/components/pages/CampaignPage.scss
  src/components/pages/org/ConnectLink.jsx
  src/server/app.js
  src/server/ops.js
  src/server/preloader.js
  src/store/actions.js
  src/store/campaigns.js
Labels: feature

#219 Redesign landing page Sign up splash
  locale/misc/en.yaml
  locale/pages/landing/da.yaml
  locale/pages/landing/en.yaml
  locale/pages/landing/sv.yaml
  src/components/App.jsx
  src/components/header/Logo.jsx
  src/components/header/Logo.scss
  src/components/misc/SignUpForm.jsx
  src/components/misc/SignUpForm.scss
  src/components/pages/landing/LandingPage.jsx
  src/components/pages/landing/SignUpSplash.jsx
  src/components/pages/landing/SignUpSplash.scss
  src/components/pages/org/OrgContent.scss
  static/images/z-logo.png
Labels: enhancement

#227 Resend verification
  locale/pages/verify/da.yaml
  locale/pages/verify/en.yaml
  locale/pages/verify/sv.yaml
  src/components/pages/VerifyEmailPage.jsx
  src/components/pages/VerifyEmailPage.scss
  src/server/app.js
Labels: enhancement, feature

#232 Add orgList attribute to CampaignForm on campaign page
  src/components/pages/CampaignPage.jsx
Labels: bug

#236 Campaign 404
  locale/pages/campaign/en.yaml
  locale/pages/campaign/sv.yaml
  package.json
  src/components/pages/CampaignPage.jsx
  src/components/pages/CampaignPage.scss
  src/server/app.js
Labels: enhancement
